# Generated by Django 4.2 on 2023-04-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_staff_id_student_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='staff',
            new_name='staff_id',
        ),
    ]
