# Generated by Django 4.2 on 2023-04-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('student', '0004_rename_staff_student_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='student',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
            preserve_default=False,
        ),
    ]
